export const PROMPT = [
    'What is cryptocurrency?',
    'How does Bitcoin work?',
    'What is the difference between Bitcoin and Ethereum?',
    'What is a blockchain?',
    'What is DeFi (Decentralized Finance)?',
    'How do I create a crypto wallet?',
    'What is the safest way to store crypto?',
    'What are NFTs and how do they work?',
    'What is a stablecoin?',
    'What does it mean to mine cryptocurrency?',
    'What is staking in crypto?',
    'What is the difference between mining and staking?',
    'How do smart contracts work?',
    'What is a Layer 1 blockchain?',
    'What is a Layer 2 solution?',
    'What is tokenomics?',
    'What’s the difference between a coin and a token?',
    'How can I earn passive income with crypto?',
    'What is an ICO (Initial Coin Offering)?',
    'What is an airdrop in crypto?',
    'How do I claim a crypto airdrop?',
    'What is the difference between an ICO, IEO, and IDO?',
    'What is Web3?',
    'How do crypto wallets work?',
    'What is a hot wallet vs a cold wallet?',
    'How secure are hardware wallets?',
    'What is a private key?',
    'What happens if I lose my wallet’s seed phrase?',
    'What is a DEX (Decentralized Exchange)?',
    'What is Uniswap?',
    'What are liquidity pools?',
    'How do I provide liquidity on a DEX?',
    'What are gas fees?',
    'Why are Ethereum gas fees so high?',
    'How do I bridge tokens between blockchains?',
    'What is a cross-chain protocol?',
    'What is a DAO (Decentralized Autonomous Organization)?',
    'What is the metaverse in crypto?',
    'What is a rug pull?',
    'How do I spot a crypto scam?',
    'How do I research a crypto project?',
    'What is market cap in crypto?',
    'What does TVL (Total Value Locked) mean?',
    'What are meme coins?',
    'Is Dogecoin a good investment?',
    'What is the role of Bitcoin halving?',
    'What is proof of work?',
    'What is proof of stake?',
    'What is Solana?',
    'What is Avalanche (AVAX)?',
    'How does Cardano (ADA) differ from Ethereum?',
    'What is Polkadot (DOT)?',
    'What is Chainlink (LINK)?',
    'What is the Lightning Network?',
    'What is a crypto faucet?',
    'What is HODL?',
    'What is FOMO in crypto?',
    'What is FUD in crypto?',
    'What is yield farming?',
    'What is an LP token?',
    'How are crypto prices determined?',
    'What is a crypto whitelist?',
    'What are testnets and mainnets?',
    'How do airdrop farming strategies work?',
    'What is zk-SNARK?',
    'What is zk-rollup?',
    'What is optimistic rollup?',
    'What are oracles in crypto?',
    'What is on-chain vs off-chain data?',
    'What is a hard fork?',
    'What is a soft fork?',
    'What is token burning?',
    'What is slippage in trading?',
    'How does arbitrage work in crypto?',
    'What is impermanent loss?',
    'What are wrapped tokens?',
    'What is WETH or WBTC?',
    'What is a multisig wallet?',
    'How do DAOs make decisions?',
    'What is governance in crypto?',
    'What is a validator node?',
    'What is the purpose of crypto indexes?',
    'What is a rebase token?',
    'What are synthetic assets in DeFi?',
    'What is a flash loan?',
    'What is TVL in DeFi?',
    'How do lending protocols work?',
    'What is the difference between CeFi and DeFi?',
    'What is a crypto launchpad?',
    'What is GameFi?',
    'What is Play-to-Earn (P2E)?',
    'How do crypto games generate revenue?',
    'What are crypto trading bots?',
    'What is technical analysis in crypto?',
    'What is fundamental analysis in crypto?',
    'What are candlestick patterns?',
    'What is a pump and dump scheme?',
    'How to track crypto portfolios?',
    'What is CoinMarketCap vs CoinGecko?',
    'What is the best way to buy crypto with fiat?',
    'What are KYC and AML in crypto exchanges?',
    'What are some good crypto security tips?',
    'What are some top crypto YouTube channels or blogs?',
    'What are some promising crypto trends for the future?',
]
